### ISSUE TITLE
[Localization] Incorrect Korean translations in "Light Theme" related strings

### ISSUE THREAD

**Issue by Coding-Young** [microsoft/calculator#1494]
**Describe the bug**

There're wrong translations in ko-KR resource file.

https://github.com/microsoft/calculator/blob/6a34a31ec6c072fb593c877ae81a070739f44a2f/src/Calculator/Resources/ko-KR/Resources.resw#L4025-L4028

https://github.com/microsoft/calculator/blob/6a34a31ec6c072fb593c877ae81a070739f44a2f/src/Calculator/Resources/ko-KR/Resources.resw#L4037-L4040

The values above should be "항상 밝게".

**Steps To Reproduce**

None

**Expected behavior**

As described above.

**Screenshots**

![image](https://user-images.githubusercontent.com/73321845/107950154-b0385400-6fd9-11eb-9904-71e0b558fe0a.png)

**Device and Application Information**
 

 - OS Build: 10.0.19042.0
 - Architecture: X64
 - Application Version: 10.2012.21.0
 - Region: ko-KR
 - Dev Version Installed: False

**Additional context**

None

**Comment by grochocki** [comment]
Thanks, @Coding-Young! We are unable to make localization fixes in GitHub directly, but I will pass this bug along to one of our internal partners to help address.
