### ISSUE TITLE
Implement "maximum characters"

### ISSUE THREAD

**Issue by hyper441** [microsoft/calculator#1694]
If possible, I would like to implement "maximum characters" so basically what I mean by maximum characters is if someone - is doing for example 9999999999999999999999999999+99999999999999999999999999 there can be a character limit to only about maybe 14 characters or maybe less or more i dont know if this is implement already if not maybe you can add it because people can be quite silly with the calculator. I'm just suggesting this idea. I don't want to implement it but if its good enough, implement it. Thank you, please read and check over this, bye.

**Comment by grochocki** [comment]
Thanks for the suggestion! In general, we do not want to limit input to any values that the calculator supports. In fact, we'd like to expand the number of supported characters in standard mode (#162). Perhaps your use case might be addressed through support for significant figures (#664) and/or rounding (#1568)?
