### ISSUE TITLE
Calculator buttons are blurry

### ISSUE THREAD

**Issue by ghost** [microsoft/calculator#1713]
You can see that the buttons in the flyout have sharp borders, while the other ones are blurry. This also happened in the past, when the buttons used reveal highlight.
![image](https://user-images.githubusercontent.com/84711285/136270241-716f766a-160e-45e9-bdc7-b89bebd04494.png)

```
 - OS Build: 10.0.22000.0
 - Architecture: X64
 - Application Version: 11.2109.8.0
 - Region: en-US
 - Dev Version Installed: False
```

**Comment by moruoxian** [comment]
Is that  Windows 11 ？  i see the border-radius ，it looks pretty than Windows 10。 :+1:
