### ISSUE TITLE
[Localization] Both milliseconds and microseconds are shown as milliseconds on ko-KR localization

### ISSUE THREAD

**Issue by copyrat90** [microsoft/calculator#1719]
Both `milliseconds(밀리초)` and `microseconds(마이크로초)` are shown as `milliseconds(밀리초)` on ko-KR localization.
It is fairly misleading, I hope it gets fixed soon.

![image](https://user-images.githubusercontent.com/34793045/137114257-4a3ac008-6507-4995-90de-fef4185473ae.png)

**Comment by copyrat90** [comment]
It is the latest version.
Actually, this issue still remains on the latest `master` branch.
I know this repository doesn't accept the localization PR, but I created a PR to show that it still exists on the master branch.
#1720 

```powershell
 - OS Build: 10.0.19043.0
 - Architecture: X64
 - Application Version: 10.2103.8.0
 - Region: ko-KR
 - Dev Version Installed: True
```

![image](https://user-images.githubusercontent.com/34793045/137242014-caaef8ee-f192-4920-92e7-085e40d73f4d.png)

**Comment by grochocki** [comment]
Already routed this to our internal localization team, so closing this.
