### ISSUE TITLE
[Localization] Missing/wrong localizations at the unit byte on data

### ISSUE THREAD

**Issue by joonas-yoon** [microsoft/calculator#1725]
**Describe the bug**

In my version as below, the text for 'Gigabyte' is showing `GB` in Korean. But it is still in english word.
(look at the attached screenshots)

**Steps To Reproduce**

- (in Windows 10, if system language is not korean)
- 1. Select Start > Settings > Time & language > Language & region
- 2. Choose language 'Korean' or add
1. Go to 'Converter > Data'
2. Click on the unit to show options
3. See translations

**Expected behavior**

Contextually I think, the word for it is `기가바이트`. Also, many items have same problem:

| English | Korean (current) | Suggestion | description |
| - | - | - | - |
| Bits | 비트 | 비트 | |
| **Bytes** | **바이트 수** | **바이트** | `수` is useless (it means unit/number in korean) |
| **Kilobits** | **Kbps** | **킬로비트** | wrong translation, `Kbps` means bitrate for 'Kilobits Per Second' |
| Kibibits | 키비비트 | 키비비트 | |
| Kilobytes | 킬로바이트 | 킬로바이트 | |
| Kibibytes | 키비바이트 | 키비바이트 | |
| Megabits | 메가비트 | 메가비트 | |
| Mebibits | 메비바이트 | 메비비트 | wrong translation, it's '비트' for bits, not '바이트' |
| Megabytes | 메가바이트 | 메가바이트 | |
| Mebibytes | 메비바이트 | 메비바이트 | |
| Gigabits | 기가비트 | 기가비트 | |
| **Gibibits** | **기비비트(비트)** | **기비비트** | `(비트)` is useless |
| **Gigabytes** | **GB** | **기가바이트** | missing translation |
| Gibibytes | 기비바이트 | 기비바이트 | |
| Terabits | 테라비트 | 테라비트 | |
| Tebibits | 테비비트 | 테비비트 | |
| Terabytes | 테라바이트 | 테라바이트 | |
| Tebibytes | 테비바이트 | 테비바이트 | |
| Petabits | 페타비트 | 페타비트 | |
| Pebibits | 페비비트 | 페비비트 | |
| Petabytes | 페타바이트 | 페타바이트 | |
| Pebibytes | 페비바이트 | 페비바이트 | |
| Exabits | 엑사비트 | 엑사비트 | |
| **Exbibits** | **엑시비비트** | **엑스비비트** | typo |
| Exabytes | 엑사바이트 | 엑사바이트 | |
| Exbibytes | 엑스비바이트 | 엑스비바이트 | |
| Zetabits | 제타비트 | 제타비트 | |
| Zebibits | 제비비트 | 제비비트 | |
| Zetabytes | 제타바이트 | 제타바이트 | |
| Zebibytes | 제비바이트 | 제비바이트 | |
| Yottabit | 요타비트 | 요타비트 | |
| Yobibits | 요비비트 | 요비비트 | |
| Yottabyte | 요타바이트 | 요타바이트 | |
| Yobibytes | 요비바이트 | 요비바이트 | |

**Furthermore**

In my opinion, the Korean texts look very similar to each others, for example '기가바이트' and '기비바이트'
it makes hard to read. thus, I think that list down with unit symbol for short is better to read as like `기가바이트(GB)`

**Screenshots**

In korean,
![image](https://user-images.githubusercontent.com/9527681/137649927-92bcac40-13a5-4ee8-846c-8cd2bbd2d607.png)

In English,
![image](https://user-images.githubusercontent.com/9527681/137593577-f5a30c32-923a-4112-af9f-e9cbabc9abdc.png)

**Device and Application Information**
- OS Build: 10.0.19043.0
- Architecture: X64
- Application Version: 10.2103.8.0
- Region: ko-KR
- Dev Version Installed: False

**Comment by hanzhang54** [comment]
Thanks @joonas-yoon , this is a very detailed table! We'll fix this as well soon.

**Comment by grochocki** [comment]
Already routed this to our internal localization team, so closing this issue.
