### ISSUE TITLE
[Localization] wrong word for 'Degrees' on Angle

### ISSUE THREAD

**Issue by joonas-yoon** [microsoft/calculator#1726]
**Describe the bug**

Having wrong translation on Angle

**Expected behavior**

| English | Korean (current) | Fix to |
| - | - | - |
| Degrees | 온도 | 도 |

Also, `grad` at bottom for displaying "About equal to ~" translated wrong.
`0 grad` is not `0 대학원생`  in korean, "대학원생" means graduate student. 🤣 
`0 도` is right.

**Screenshots**

![image](https://user-images.githubusercontent.com/9527681/137650246-41b8f7a1-bbfa-4892-8176-a9726e78d60a.png)

**Device and Application Information**
 - OS Build: 10.0.19043.0
 - Architecture: X64
 - Application Version: 10.2103.8.0
 - Region: en-US
 - Dev Version Installed: False

**Comment by grochocki** [comment]
Thanks for the feedback! We need to route this to our internal localization team, so closing this issue.
