### ISSUE TITLE
It would be great if you could copy output without commas.

### ISSUE THREAD

**Issue by tony-azevedo** [microsoft/calculator#1813]
**Problem Statement**

**Evidence or User Insights**

**Proposal**

**Goals**

**Non-Goals**

**Low-Fidelity Concept**

**Requested Assignment**

If possible, I would like to implement this.
I'm just suggesting this idea.  I don't want to implement it.

**Comment by erinrshi** [comment]
Hi, can I be assigned this task?

**Comment by mcooley** [comment]
It looks like this was suggested before in #1305. In #1331, there is a suggestion that we could resolve this by adding _both_ plain text (without separators) and rich text (with separators) to the clipboard. We can discuss this idea further in that thread.
