### ISSUE TITLE
Simple 'fix' for undocumented hotkeys

### ISSUE THREAD

**Issue by tshinnic** [microsoft/calculator#1814]
So many issues have touched upon hotkeys being difficult to discover. It was revealing to see someone mention that toggling the Alt key was one partial method. Nice... 

But otherwise there's no online help and no documentation to consult. I saw mention of a possible web search target of [Keyboard shortcuts in apps](https://support.microsoft.com/en-us/windows/keyboard-shortcuts-in-apps-139014e7-177b-d1f3-eb2e-7298b2599a34#bkmk_cal), back when someone mentioned that page was 'new' (in 2019?!)  Kind of unfortunate the in-page links there don't work though... nor the HTML entities...

But wait! There's a real simple 'fix. The nearest thing you've got to a link to online help is ín the "About" popup from the window hamburger menu, which (at the bottom of the popup) has a link to *here*, **Github**.  Which shows the **[README.md](https://github.com/Microsoft/calculator#readme)**!  Online!

And if only that readme (quite often used for usage information by other projects) had... keyboard shortcuts documented... wow!

I've copy-n-pasted and markdown'ed that text below:

Press this key | To do this
-- | --
Alt + 1 | Switch to Standard mode
Alt + 2 | Switch to Scientific mode
Alt + 3 | Switch to Graphing mode
Alt + 4 | Switch to Programmer mode
Alt + 5 | Switch to Date Calculation mode
Ctrl + M | Store in memory, in Standard mode, Scientific mode, and Programmer mode
Ctrl + P | Add to memory, in Standard mode, Scientific mode, and Programmer mode
Ctrl + Q | Subtract from memory, in Standard mode, Scientific mode, and Programmer mode
Ctrl + R | Recall from memory, in Standard mode, Scientific mode, and Programmer mode
Ctrl + L | Clear memory
Delete | Clear current input (select CE)
Esc | Fully clear input (select C)
Tab | Navigate to the next UI item and give it focus
Spacebar | Selects UI item that has focus
Enter | Selects = in Standard mode, Scientific mode, and Programmer mode
F9 | Select **+/-** in Standard mode, Scientific mode, and Programmer mode
R | Select **1/x** in Standard mode and Scientific mode
@ | Select <sup>**2**</sup>**√x** in Standard mode and Scientific mode
% | Select **%** in Standard mode and Programmer mode
Ctrl + H | When history button is visible, selects the history button in Standard mode and Scientific mode
Up arrow | Move up in history list, memory list, and menu items
Down arrow | Move down in history list, memory list, and menu items
Ctrl + Shift + D | Clear history
F3 | Select **DEG** in Scientific mode
F4 | Select **RAD** in Scientific mode
F5 | Select **GRAD** in Scientific mode
G | Select **2**<sup>**x**</sup> in Scientific mode
Ctrl + G | Select **10**<sup>**x**</sup> in Scientific mode
S | Select **10**<sup>**x**</sup> in Scientific mode
Shift + S | Select **sin**<sup>**-1**</sup> in Scientific mode
Ctrl + S | Select **sinh** in Scientific mode
Ctrl + Shift + S | Select **sinh**<sup>**-1**</sup> in Scientific mode
T | Select **tan** in Scientific mode
Shift + T | Select **tan**<sup>**-1**</sup> in Scientific mode
Ctrl + T | Select **tanh** in Scientific mode
Ctrl + Shift + T | Select **tanh**<sup>**-1**</sup> in Scientific mode
O | Select **cos** in Scientific mode
Shift + O | Select **cos**<sup>**-1**</sup> in Scientific mode
Ctrl + O | Select **cosh** in Scientific mode
Ctrl + Shift + O | Select **cosh**<sup>**-1**</sup> in Scientific mode
U | Select **sec** in Scientific mode
Shift + U | Select **sec**<sup>**-1**</sup> in Scientific mode
Ctrl + U | Select **sech** in Scientific mode
Ctrl + Shift + U | Select **sech**<sup>**-1**</sup> in Scientific mode
I | Select **csc** in Scientific mode
Shift + I | Select **csc**<sup>**-1**</sup> in Scientific mode
Ctrl + I | Select **csch** in Scientific mode
Ctrl + Shift + I | Select **csch**<sup>**-1**</sup> in Scientific mode
J | Select **cot** in Scientific mode
Shift + J | Select **cot**<sup>**-1**</sup> in Scientific mode
Ctrl + J | Select **coth** in Scientific mode
Ctrl + Shift + J | Select **coth**<sup>**-1**</sup> in Scientific mode
Ctrl + Y | Select <sup>**y**</sup>**√x** in Scientific mode
Shift + \ | Select **\|x\|** in Scientific mode
[ | Select **&lfloor;x&rfloor;** in Scientific mode 
] | Select **&lceil;x&rceil;** in Scientific mode
L | Select **log** in Scientific mode
Shift + L | Select **log**<sub>**y**</sub><sup>**x**</sup> in Scientific mode
M | Select **dms** in Scientific mode
N | Select **ln** in Scientific mode
Ctrl + N | Select **e**<sup>**x**</sup> in Scientific mode
P | Select **Pi** in Scientific mode
Q | Select **x**<sup>**2**</sup> in Standard mode and Scientific mode
V | Toggles on/off **F-E** buttonin Scientific mode
X | Select **exp** in Scientific mode
Y, ^ | Select **x**<sup>**y**</sup> in Scientific mode
 &#35; | Select **x**<sup>**3**</sup> in Scientific mode
! | Select **n!** in Scientific mode
% | Select **mod** in Scientific mode
Ctrl ++ on numpad | Graph zooms in while in Graphing mode
Ctrl +- on numpad | Graph zooms out while in Graphing mode
F2 | Select **DWORD** in Programmer mode
F3 | Select **WORD** in Programmer mode
F4 | Select **BYTE** in Programmer mode
F5 | Select **HEX** in Programmer mode
F6 | Select **DEC** in Programmer mode
F7 | Select **OCT** in Programmer mode
F8 | Select **BIN** in Programmer mode
F12 | Select QWORD in Programmer mode
A-F | Select letters A-F in Programmer mode while **HEX** is selected
Shift + , | Select **RoL** in Programmer mode when Bit Shift is set to either "Circular" shift
Shift + . | Select **RoR** in Programmer mode when Bit Shift is set to either "Circular" shift
Shift + , | Select **Lsh** in Programmer mode when Bit Shift is set to "Arithmetic" or "Logical" shift
Shift + . | Select **Rsh** in Programmer mode when Bit Shift is set to "Arithmetic" or "Logical" shift
% | Select **%** in Programmer mode
\| | Select **OR** in Programmer mode
^ | Select **XOR** in Programmer mode
\ | Select **NOR** in Programmer mode
~ | Select **NOT** in Programmer mode
& | Select **AND** in Programmer mode
. | Select **NAND** in Programmer mode

Please consider adding this usage information to the README.md.

**Comment by mcooley** [comment]
The [Keyboard shortcuts in apps page](https://support.microsoft.com/en-us/windows/keyboard-shortcuts-in-apps-139014e7-177b-d1f3-eb2e-7298b2599a34) is the official documentation for this. Instead of duplicating the content, we'd rather fix the existing page. I've submitted a request internally to get the in-page links fixed. 

I don't think it's wise to add a duplicate copy of this documentation in the README. Mixing end-user and developer content can make it harder for both audiences to find the information they need.
