### ISSUE TITLE
[Localization] Incorrect word for 'Domain' in graphing mode 

### ISSUE THREAD

**Issue by toto6038** [microsoft/calculator#1816]
**Describe the bug**

The text 'domain' is incorrectly translated to 網域 in Traditional Chinese (Taiwan). 網域 is the term used in computer networking contexts and has nothing to do with the text here. It fails to convey idea to users and cause confusion.

**Steps To Reproduce**

1. Go to 'Graphing'(繪圖) via hamburger menu at the upper-left corner
2. Click on 'Switch to formula mode'(切換到方程式模式) at the upper-right corner
3. Input a function, e.g. `abs(x)`
4. Click on 'Analyze function'(分析函式)
5. See the error

**Expected behavior**

Domain should be translated to 定義域, [reference to dictionary from National Academy for Educational Research](https://terms.naer.edu.tw/detail/1218760/).

**Screenshots**

![圖片](https://user-images.githubusercontent.com/50100922/161127413-26b950e2-8b38-46c9-8325-9f6f654fe6ca.png)
**Device and Application Information**
 - OS Build: 10.0.19044.0
 - Architecture: X64
 - Application Version: 10.2103.8.0
 - Region: zh-TW
 - Dev Version Installed: None

**Additional context**

An extra suggestion: change the translation of the aforementioned 'Analyze function' from 分析函式 to 分析函數 to keep consistency with others as 'function' is translated to 函數 except 'Function Analysis' and 'Analyze function' in Graphing mode, e.g. 'Trigonometric function' <=> 三角函數 and 'Function' <=> 函數.

**Comment by mcooley** [comment]
Thanks for the suggestion! I have filed an internal issue (44599744) to track this feedback. Our localization team will review and apply the changes.

**Comment by mcooley** [comment]
Addressed in #2013

**Comment by mcooley** [comment]
The translation for "Domain" was updated by our localization team in #2013.

**Comment by Firestar-Reimu** [comment]
But #2013 translated it to "领域" instead of "定义域" @toto6038

**Comment by toto6038** [comment]
@Firestar-Reimu Thanks for keeping me updated!
