### ISSUE TITLE
Visual Studio 2022 17.2 cannot open Calculator.sln

### ISSUE THREAD

**Issue by sunjw** [microsoft/calculator#1831]
**Describe the bug**
Visual Studio 2022 17.2 cannot open Calculator.sln

**Steps To Reproduce**
1. Launch Visual Studio 2022 17.2 (must be 17.2)
2. Open Calculator.sln

**Expected behavior**
Load Calculator.sln (17.1 works well) 

**Screenshots**
![Bdb11d7cbd9b14ba69572b83f018289ec637880606052446961_20220513-124325-image](https://user-images.githubusercontent.com/846335/168409605-001f5809-76bd-4314-9c7b-96bbea84796b.png)

**Device and Application Information**
 - OS Build:
 - Architecture:
 - Application Version:
 - Region:
 - Dev Version Installed:

Just like this one
https://developercommunity2.visualstudio.com/t/VS-1720-Wont-open-sln-reports-that-i/10042021?q=%5BVisual+Studio+2022+version+17.2%5D+solution&ftype=problem&space=8&stateGroup=active&sort=newest

Maybe an issue in VS 2022 17.2.

**Comment by MarcoBonino** [comment]
I confirm I have the same issue.
I found out a solution, but not clear why it works:
change `VisualStudioVersion = 17` with `VisualStudioVersion = 17.0`.
My guess is that the version checker removes the dots in version and just compare that `VisualStudioVersion` number is strictly greater than `VisualStudioVersion = 17.0`.
In this case something like 170 > 17.

To confirm this idea, this works:
VisualStudioVersion = 17.0
MinimumVisualStudioVersion = 16.9

but not this:
VisualStudioVersion = 17
MinimumVisualStudioVersion = 16.9

**Comment by mattyyzac** [comment]
same trouble here.
but I cannot make it correct by changing VisualStudioVersion  and MinimumVisualStudioVersion shown above 😒

**Comment by AdamKxZ** [comment]
> I confirm I have the same issue. I found out a solution, but not clear why it works: change `VisualStudioVersion = 17` with `VisualStudioVersion = 17.0`. and `MinimumVisualStudioVersion = 17` with `MinimumVisualStudioVersion = 17.0`.

Can confirm this fixed the issue on my end.
