### ISSUE TITLE
@weinand I needed more granular control to solve the issue - whether F keys are on by default or not, I still was getting OSX overriding VS Code's F11 (in one case holding Fn+F11, in the other case hitting F11).

### ISSUE THREAD

**Issue by limalex88** [microsoft/calculator#1840]
@weinand I needed more granular control to solve the issue - whether F keys are on by default or not, I still was getting OSX overriding VS Code's F11 (in one case holding Fn+F11, in the other case hitting F11).

_Originally posted by @lukewlms in https://github.com/microsoft/vscode/issues/5102#issuecomment-245733375_

**Comment by weinand** [comment]
@limalex88 I'm a dev on the VS Code team - I have nothing to do with a "calculator"
