### ISSUE TITLE
Calculator failed to build with "error MSB3271: There was a mismatch between the processor architecture of the project being built "" and the processor architecture, "AMD64"" with MSVC on Windows arm64ec

### ISSUE THREAD

**Issue by YangYang129** [microsoft/calculator#1853]
Calculator failed to build with "error MSB3271: There was a mismatch between the processor architecture of the project being built "" and the processor architecture, "AMD64"" with MSVC on Windows arm64ec. It can reproduce on latest version https://github.com/microsoft/calculator/commit/91adfd8e9e14b9719e51f4c5e2e06380b6f429cc on master branch. Could you please help look at this issue?

**Repro steps:**
1. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=arm64
2. git clone https://github.com/microsoft/calculator F:\calculator
3. cd F:\calculator
4. set PATH=F:\Agent\_work\1\s\src\tools\nuget;%PATH%
5. cd src
6. Change "ARM64" to "ARM64EC" in Calculator.csproj TraceLogging.vcxproj CalcManager.vcxproj GraphingImpl.vcxproj Calculator.sln GraphControl.vcxproj CalcViewModel.vcxproj file
7. nuget.exe restore -ConfigFile F:\calculator\src\nuget.config Calculator.sln
8. msbuild /m /p:Platform=ARM64EC /p:Configuration=Release /p:WindowsTargetPlatformVersion=10.0.22618.0 /p:PlatformToolset=v142 Calculator.sln /t:Rebuild

**Error info:**
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2203,5): error MSB3271: There was a mismatch between the processor architecture of the project being built "" and the processor architecture, "AMD64", of the implementation file "F:\calculator\src\ARM64EC\Release\TraceLogging\TraceLogging.dll" for "F:\calculator\src\ARM64EC\Release\TraceLogging\TraceLogging.winmd". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and implementation file, or choose a winmd file with an implementation file that has a processor architecture which matches the targeted processor architecture of your project. [F:\calculator\src\GraphControl\GraphControl.vcxproj]`

**Error Log:**
[Calculator_build_arm64ec.log](https://github.com/microsoft/calculator/files/8897753/Calculator_build_arm64ec.log)

**Comment by mcooley** [comment]
Currently Calculator builds with Visual Studio 2022 and the v143 build tools. We can't guarantee that the project will build correctly with Visual Studio 2019 and v142 build tools like you're trying here.
