### ISSUE TITLE
help! how to install calc offline....

### ISSUE THREAD

**Issue by mao-china** [microsoft/calculator#1863]
Anyone could give me some suggestions, how to install calc and my computer in laboratory is offline?
Thanks a lot!

**Comment by denyaalt** [comment]
I have the same problem. 
Please post the compiled exe file.

**Comment by mao-china** [comment]
@denyaalt 
finally, i restored my windows for calc, how stupid, it's the only way i can use it.

**Comment by grochocki** [comment]
You can get the latest version of Calculator in the [Microsoft Store](https://www.microsoft.com/store/apps/9WZDNCRFHVN5). Unfortunately, offline installation is not available, but you can build from this project and deploy locally.
