### ISSUE TITLE
Trig functions are not working when divided

### ISSUE THREAD

**Issue by G0D-Developer** [microsoft/calculator#1873]
**Describe the bug**
The trig functions when used by themselves are working, but when performing an expression such as *4/cos(55 degrees)* the calculator responds with a solution of 0.57, however, the real answer is 6.97. Similar issues occur when having a trig function as the denominator of a fraction (or division expression).  

**Steps To Reproduce**
1. Open the side menu
2. Click the *Scientific* option
3. Type '4/cos(55)' *make sure the mode is in degrees not radians
4. The result displayed 0.57 instead of 6.97

**Expected behavior**
The output should've been 6.97 

**Screenshots**

![Trig Func not working calc](https://user-images.githubusercontent.com/75747985/181865029-1f226491-9dbf-430d-84ed-7ab2057548e7.png)

**Device and Application Information**
 - OS Build: 18363.2274
 - Architecture: x64
 - Application Version: 10.2103.8.0
 - Region: en-US
 - Dev Version Installed: False

**Additional context**

The 4/cos(55 degrees) was one of the many examples. There are also other expressions with similar problems.  

**Requested Assignment**

I'm just reporting this problem. I don't want to fix it.

**Comment by RajAt17k** [comment]
There is no issue , you have to press "=" to get final result.
0.57 is value of cos 55 i.e the current operation in progress , press "=" and you get 6.97

**Comment by G0D-Developer** [comment]
Thanks for letting me know!
