### ISSUE TITLE
There should be options to go less than microseconds

### ISSUE THREAD

**Issue by saleem0915** [microsoft/calculator#1949]
**Problem Statement**

**Evidence or User Insights**

**Goals**

**Non-Goals**

**Low-Fidelity Concept**

**Requested Assignment**

**Comment by Overruler** [comment]
Currently, I need to go to Google every time I see something like "0.85us ±150ns" in a datasheet. Smaller units that cover timing ranges in today's microprocessors should be included in Calculator.

**Comment by saleem0915** [comment]
So, you're basically saying that you agree?
________________________________

**Comment by Overruler** [comment]
Yes, totally.

**Comment by saleem0915** [comment]
I'm not sure if development has gone on for this issue so I will be marking it as closed. If this changes, I will gladly reopen this issue.

Thank you.
