### ISSUE TITLE
Calculator crashes when try copy to clipboard

### ISSUE THREAD

**Issue by Deoptim** [microsoft/calculator#1971]
**Describe the bug**

When I try to copy to clipboard any data (or just empty data on window selected of calculator) - it crashes. Any method - keyboard hotkeys Ctrl+C or click mouse menu Copy

**Steps To Reproduce**

1. Open the Calculator
2. Select window of the Calculator
3. Press hotkeys Ctrl+C (or mouse menu item - Copy)

**Expected behavior**

Previous versions of calculator is not crashes

**Screenshots**

![Screenshot](https://user-images.githubusercontent.com/5656726/213705982-c9cf9980-b77b-429b-ab0d-790bfab1c187.jpg)

**Device and Application Information**
 - OS Build: 10.0.19045.0
 - Architecture: X64
 - Application Version: 11.2210.0.0
 - Region: en-US
 - Dev Version Installed: False
Also the same issue on Windows 11 on same computer(CPU) and the same application version.

 
**Additional context**

The CPU of computer with problem has no SSE4* instructions, as I noticed, the calculator works on other computers.
After crashing the calculator in Events viewer occurs an error:
```
Faulting application name: CalculatorApp.exe, version: 11.2210.0.0, time stamp: 0x63694266
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2364, time stamp: 0x5b7d4d22
Exception code: 0xc000027b
Fault offset: 0x000000000010fe32
Faulting process id: 0x23dc
Faulting application start time: 0x01d92cd027455248
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsCalculator_11.2210.0.0_x64__8wekyb3d8bbwe\CalculatorApp.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 6a82b71f-7bf7-4a12-86a3-b6a01318f8d2
Faulting package full name: Microsoft.WindowsCalculator_11.2210.0.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

**Requested Assignment**

If possible, I would like to fix this.
I'm just reporting this problem.  I don't want to fix it.

**Comment by gir489returns** [comment]
KERNELBASE.DLL+10fe32 is not an SSE4 instruction. 0xc000027b is a UWP exception, generated when something asynchronous crashes. While the copy command could be what's initializing this function, correlation might not be causation. Simply attempting to allocate more RAM might cause the page pool to try and expand by an unknown amount, causing this error. Although I have no idea, you've given 0 context clues to the problem and what supposed CPU you think is causing this.

**Comment by Deoptim** [comment]
Solved.
It was crashed because used tweak that disabled "**cbdhsvc**" service and disabled ClipboardHistory (Telemetry issues).
Like registry parameters was zeroed:
```
HKLM:\SOFTWARE\Policies\Microsoft\Windows\System
HKCU:\Software\Microsoft\Clipboard
AllowClipboardHistory = 0x0
AllowCrossDeviceClipboard  = 0x0
EnableClipboardHistory  = 0x0
```
