### ISSUE TITLE
Missing documentation explaining keyboard input

### ISSUE THREAD

**Issue by jvillemure** [microsoft/calculator#1975]
**Problem Statement**
There's is no easy way to gain knowledge on the mapping of keyboard keys to calculator buttons.

Using mouse to write math expressions is long and tedious; keyboard should be the preferred input method (wich is similar to an physical desk calculator). With appropriate additions to the calculator software, it should be quick and easy to learn how to use it using only the keyboard.

**Evidence or User Insights**

I filed this issue today because I had some frustration while trying to type in some simple expression. I was trying to input a unary minus operator, and I had try one by one and guess which keyboard shortcut would produce unary minus. Finally found it was F9 after I search through several gh issue pages and noticed that some 'F' keys were assigned some very unusual and unintuitive behavior. IMO, the `F9` key is a very poor choice compared to the intuitive `Shift`+`-` or simply `n`.

**Proposal**

The calculator needs:
 - a user manual (software without documentation is useless software)
 -  tooltips for every calculator buttons with its current keybinding
 - a way to configure custom keybinding (so that we may change poorly chosen defaults)

**Goals**

**Non-Goals**

**Low-Fidelity Concept**

**Requested Assignment**

I'm just suggesting this idea.  I don't want to implement it.

**Comment by mcooley** [comment]
Thanks for the feedback. This has been mentioned before in #157; feel free to discuss these issues further in that thread. As mentioned in that thread, we think the best long-term direction is to provide a way to type in simple expressions _without_ learning or configuring keyboard shortcuts (#620).

For reference, [a list of the keyboard shortcuts in Calculator is available here](https://support.microsoft.com/en-us/windows/keyboard-shortcuts-in-apps-139014e7-177b-d1f3-eb2e-7298b2599a34).
