### ISSUE TITLE
Calculator Settings Won't Close

### ISSUE THREAD

**Issue by ticiadev** [microsoft/calculator#1979]
**Describe the bug**
When opening the application, the settings pane opens. After trying to close that pane, it keeps popping up, which prevents use of the calculator.

**Steps To Reproduce**
Open calculator application and attempt to close the settings pane.

**Expected behavior**
Proper closing of the settings pane to use the calculator.

**Screenshots**
![calculator-bug](https://user-images.githubusercontent.com/30507348/221002080-3727a348-0c6f-4abe-9f0a-b061e6e41753.gif)

**Device and Application Information**
 - OS Build: Windows 10 19045
 - Architecture: x64
 - Application Version: 11.2210.0.0
 - Region: en-US
 - Dev Version Installed: False

**Additional context**
n/a

**Requested Assignment**
I'm just reporting this problem.  I don't want to fix it.

**Comment by lazydevl0per** [comment]
I have tried reproducing with 

- OS Build: Windows 11 22621
- Calculator Package Release manifest: 10.1604.27012
- Target: Calculator (Universal Windows)
- Build: Debug & Release, x86 & x64

Sadly not reproducable.
Might be a Windows 10 issue?

**Comment by ticiadev** [comment]
It looks like this issue was resolved by updating Windows. I also checked on another PC with the same device/app info as mine, and it didn't have the same settings pane issue.

Thanks for looking into it!
