### ISSUE TITLE
CalculatorApp.exe is not executable...

### ISSUE THREAD

**Issue by TRJ1** [microsoft/calculator#1980]
**Describe the bug**
I try to build the Calculator for a computer without entry to the Microsoft Store. After I compile the project with Visual Studio inside my project folder the CalculatorApp.exe appears. Unfortunately this exe is not executable. Every time I try to start the exe nothing happens. When I simultaneously open the Task Manager I can see that the exe start and cancel after a few seconds. Inside the Event Viewer two error messages appear(see first two screenshots). When I debug the project in Visual Studio the calculator starts normally.
When I create a Setup Launcher for the project the application it cant installed the application probably, without the change of the Microsoft.NET dependency from .NET Framework 4.7.2 to Any, although the requested version is installed(see screenshot 3 and 4). While the build process of the Setup Launcher several warning appears(see screenshot 4 and 5). Likewise the warning before the requested dependencies are available on the system. While my search I discovered that maybe some file path are not resolved correctly(see screenshot 7). All in all i can not find the reason why the creation of a working exe is not working. Maybe some compatibility issues...
Can someone maybe describe the correct steps how to create a working exe of the Calculator?

So why run the calculator after I debug the project in Visual Studio, but not when I try to open the exe?

**Steps To Reproduce**

1. Download a version of the project with is compatible with Win 10.
2. Follow the instructions of the "Getting Started".
3. Build Solution with Visual Studio.
4. Open exe in the project folder.
5. See error

**Expected behavior**
The Calculator can be installed on the computer normally.

**Screenshots**
1.
![Screenshot (12)](https://user-images.githubusercontent.com/126459501/221536928-99ceb98a-743b-48fd-bc40-2568c88dd382.png)

2.
![Screenshot (13)](https://user-images.githubusercontent.com/126459501/221536967-872ddcb7-816f-4d94-8eba-a3529796bf89.png)

3.
![Screenshot (14)](https://user-images.githubusercontent.com/126459501/221543508-22f292a1-88a7-44b2-a491-ee32c39ff253.png)

4.
![Screenshot (15)](https://user-images.githubusercontent.com/126459501/221543554-644a5327-555c-4630-a52f-474992c31022.png)

5.
![Screenshot (16)](https://user-images.githubusercontent.com/126459501/221543594-fd798259-5551-4cfc-a5bf-8abf4fc8852c.png)

6.
![Screenshot (17)](https://user-images.githubusercontent.com/126459501/221543655-c44a4038-e869-445a-a497-89a554da0966.png)

7.
![Screenshot (18)](https://user-images.githubusercontent.com/126459501/221545880-5799001b-4973-4a14-a559-8f58494ef0b7.png)

**Device and Application Information**
 - OS Build: 10.0.20348.0
 - Architecture: x64
 - Application Version:
 - Region:de-De
 - Dev Version Installed:

**Additional context**
I work on a 2022 Server environment, but I can reproduce the error on a Win 10 Pro and a Win 11 Pro environment. 

**Requested Assignment**

If possible, I would like to fix this.

**Comment by valleeiii** [comment]
Hi, could you assign me to it so that I can try and fix the problem for you

**Comment by valleeiii** [comment]
Hi, could you assign me to this task.
