### ISSUE TITLE
[Redacted] A team member edited the title to remove content that violated this project's code of conduct

### ISSUE THREAD

**Issue by ghost** [microsoft/calculator#1981]
[Redacted]

>Note: A team member edited this comment to remove content that violated this project's [code of conduct](https://github.com/Microsoft/calculator/blob/master/CODE_OF_CONDUCT.md)., classification, and release consistently.

**Comment by zadjii-msft** [comment]
lmao

**Comment by lazydevl0per** [comment]
??? You good?
