### ISSUE TITLE
POSSIBILITA' DI STABILIRE QUANTITA' CIFRE DOPO LA VIRGOLA E CONSEGUENTE ARROTONDAMENTO -5=0 +5=1 

### ISSUE THREAD

**Issue by Luigi17156** [microsoft/calculator#1991]
ho fatto l'iscrizione per questo problema che non riesco a risolvere nella calcolatrice
di Microsoft

**Comment by Luigi17156** [comment]
Faccio un lavoro di contabilità per il quale mi bastano numeri con due ordini dopo la virgola e con l'arrotondamento come spiegato.

**Comment by mcooley** [comment]
I think this suggestion is the same idea as #485.
