### ISSUE TITLE
Bug effecting Scienctific Calulator on Windows 10

### ISSUE THREAD

**Issue by CamoCatX** [microsoft/calculator#1998]
**Describe the bug**
This bug, when done, prints "invalid input" even though the input is clearly valid

**Steps To Reproduce**

1. Go to the scientific calculator.
2.  Press the 2 key
3. Put the 2 to the power of 123,456,789
4. Press enter

**Expected behavior**
Expected behavior would be to show the correct answer  

 - OS Build: WIndows 10 home
 - Application Version: 11.2210.0.0

**Additional context**

**Requested Assignment**
I'm just reporting this problem.  I don't want to fix it.

**Comment by Flippchen** [comment]
The number you are suggesting would need a 123.456.789 bit integer (roughly 15 MB) to store it, which C# or any other programming language does not support. 😉
However, there are other solutions to work with such big numbers (https://cs.stackexchange.com/questions/140881/how-do-computers-perform-operations-on-numbers-that-are-larger-than-64-bits).

So, to conclude, the number you are trying to calculate is simply too big. No basic calculator works on such big numbers

**Comment by CamoCatX** [comment]
@Flippchen Thanks for the solution! Closing issue...
