### ISSUE TITLE
Theme exception

### ISSUE THREAD

**Issue by Jack253-png** [microsoft/calculator#2001]
**Describe the bug**
Change caclulator's theme quickly, and UI Elements' color will corrupt

**Steps To Reproduce**
Change theme quickly.

**Expected behavior**
Null

**Screenshots**
light to dark
![图片](https://github.com/microsoft/calculator/assets/83895170/2089135e-1e7b-4f40-8ad9-d6e8a360a758)
dark to light
![图片](https://github.com/microsoft/calculator/assets/83895170/3862787b-c313-4e36-bfd7-437096518ce4)

**Device and Application Information**
 - OS Build: 
 - Major  Minor  Build  Revision
    -----  -----  -----  --------
     10     0      22621  0
 - Architecture: X64
 - Application Version: 11.2210.0.0
 - Region: zh-CN
 - Dev Version Installed: False

**Requested Assignment**

If possible, I would like to fix this.
I'm just reporting this problem.  I don't want to fix it.

**Comment by mcooley** [comment]
Thanks for the bug report! I think this is the same issue as #1861.
