### ISSUE TITLE
N

### ISSUE THREAD

**Issue by syedkumailshah** [microsoft/calculator#2113]
**Describe the bug**

**Steps To Reproduce**

**Expected behavior**

**Screenshots**

**Device and Application Information**
 - OS Build:
 - Architecture:
 - Application Version:
 - Region:
 - Dev Version Installed:

**Additional context**

**Requested Assignment**

If possible, I would like to fix this.
I'm just reporting this problem.  I don't want to fix it.

**Comment by syedkumailshah** [comment]
import java.util.Scanner;

public class Calculator {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        System.out.print("Enter first number: ");
        double num1 = scanner.nextDouble();

        System.out.print("Enter operator (+, -, *, /): ");
        char operator = scanner.next().charAt(0);

        System.out.print("Enter second number: ");
        double num2 = scanner.nextDouble();

        double result;

        switch (operator) {
            case '+':
                result = num1 + num2;
                break;
            case '-':
                result = num1 - num2;
                break;
            case '*':
                result = num1 * num2;
                break;
            case '/':
                if (num2 != 0) {
                    result = num1 / num2;
                } else {
                    System.out.println("Error: Division by zero");
                    return;
                }
                break;
            default:
                System.out.println("Error: Invalid operator");
                return;
        }

        System.out.println("Result: " + result);
    }
}

**Comment by Rajdave69** [comment]
How is this related to the microsoft calculator app?
