### ISSUE TITLE
-1^2 is -1 not 1

### ISSUE THREAD

**Issue by Cmiranda365** [microsoft/calculator#2205]
**Describe the bug**

**Steps To Reproduce**

**Expected behavior**

**Screenshots**

**Device and Application Information**
 - OS Build:
 - Architecture:
 - Application Version:
 - Region:
 - Dev Version Installed:

**Additional context**

**Requested Assignment**

If possible, I would like to fix this.
I'm just reporting this problem.  I don't want to fix it.

**Comment by Cmiranda365** [comment]
Problem with -1^2 = 1, when its -1

**Comment by raven-xr** [comment]
> Problem with -1^2 = 1, when its -1

That's not a problem. Actually, -1^2 = 1. You square one, and not the minus behind it. And you get -(1*1) = -1. But if we take -1 in parentheses we get (-1)^2 that really gives us 1

**Comment by KParthSingh** [comment]
What. -1^2 is 1 not -1 is this a troll report?

**Comment by WarFiN123** [comment]
> What. -1^2 is 1 not -1 is this a troll report?

this is not a troll report. u can search it on google. -1^2 = -1 whereas (-1)^2 = 1. Hope this helps

**Comment by KParthSingh** [comment]
> -1^2 = -1 whereas (-1)^2 = 1. Hope this helps
Fuck my life was a life. You're right

**Comment by MovGP0** [comment]
I think we should close this issue

**Comment by WarFiN123** [comment]
> I think we should close this issue

Why so?

**Comment by raven-xr** [comment]
> > I think we should close this issue
> 
> Why so?

Because -1^2 = -1 but (-1)^2 = 1. You shouldn't have skipped your math lessons (no negative)

**Comment by WarFiN123** [comment]
> > > I think we should close this issue
> > 
> > 
> > Why so?
> 
> Because -1^2 = -1 but (-1)^2 = 1. So the issue isn't actually an issue. You shouldn't have skipped your math lessons (no negative)
> 
> ![image](https://private-user-images.githubusercontent.com/173906961/364615245-f139f8a0-2acb-4860-8945-a61d8c032602.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NTcwMTMsIm5iZiI6MTcyNTU1NjcxMywicGF0aCI6Ii8xNzM5MDY5NjEvMzY0NjE1MjQ1LWYxMzlmOGEwLTJhY2ItNDg2MC04OTQ1LWE2MWQ4YzAzMjYwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQxNzE4MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Njg4MWNiMDE3ZGE4OTU4YjFlYmExNjNhODA0M2RlYTdhODY0N2U4ZTY1ZmRhZjBmMDA4Y2ZiMTY4YjA0ZjRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8q9jv5CDcWtoFefqAlEi2vNogROyGJLwfgMMbNEtQ34)
> 
> ![image](https://private-user-images.githubusercontent.com/173906961/364615532-6fe0ed55-2d2f-45ad-89cc-24d0e280c6b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NTcwMTMsIm5iZiI6MTcyNTU1NjcxMywicGF0aCI6Ii8xNzM5MDY5NjEvMzY0NjE1NTMyLTZmZTBlZDU1LTJkMmYtNDVhZC04OWNjLTI0ZDBlMjgwYzZiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQxNzE4MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NmQ3NjA3ZGFmYjNiY2E5NzRiYzcyZTY3NzgyZjdlNWUxOWRhYmNkMWIzODdiZTc4MDY5ZWY2ZDVjNGIzZGE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IHqEQqKBybQ6st15B4A1yy6_-BtQ-7IEAeCn58fJIwQ)

that is exactly what i was saying, the windows calculator showed 1 for -1^2. Now, its fixed now and it shows -1.

**Comment by WarFiN123** [comment]
maybe you should've paid more attention to your english classes?
