### ISSUE TITLE
Italics = Bad

### ISSUE THREAD

**Issue by Joel-Sullivan** [microsoft/calculator#2228]
**Describe the bug**

**Steps To Reproduce**

**Expected behavior**

**Screenshots**

**Device and Application Information**
 - OS Build:
 - Architecture:
 - Application Version:
 - Region:
 - Dev Version Installed:

**Additional context**

**Requested Assignment**

If possible, I would like to fix this.
I'm just reporting this problem.  I don't want to fix it.

**Comment by MichaelK-F** [comment]
I think this might be a troll. Just a hunch.
