### ISSUE TITLE
Calculator stopped supported scientific notation

### ISSUE THREAD

**Issue by mlongtin0** [microsoft/calculator#2237]
**Describe the bug**
Scientific notation doesn't work for the calculator anymore.
I could swear "1e9/20" would give me 50000000 until a few weeks ago, but now it offers to open a URL (https://1e9/20).

**Steps To Reproduce**
1. Alt-tab
2. Type "1e9/20" or "=1e9/20"

**Expected behavior**
50000000
**Screenshots**
![image](https://github.com/user-attachments/assets/bd7738d2-2ca7-4f0c-b240-b1162fcde7eb)

**Device and Application Information**
 - OS Build: 22631.4169
 - Architecture: Intel
 - Application Version: v0.84.1
 - Region: US
 - Dev Version Installed:No

**Additional context**

**Requested Assignment**

If possible, I would like to fix this.
I'm just reporting this problem.  I don't want to fix it.

**Comment by dmex** [comment]
> Scientific notation doesn't work for the calculator anymore.

Your screenshot looks like the third party calculator like one installed with Microsoft PowerToys? This repository is for issues with the Windows Calculator which is a different application managed by a different team.

> Application Version: v0.84.1

The latest version of the Windows Calculator is `11.2409.0.0` 

v0.84.1 would be the previous release of Microsoft PowerToys. You'll need to report the issue with the PowerToys Calculator here:
https://github.com/microsoft/PowerToys

**Comment by mlongtin0** [comment]
Yes, my bad, not sure how I ended here instead of PowerToys.
