### ISSUE TITLE
Wrong calculation in Programmer mode: 3000 * 80 = -22144

### ISSUE THREAD

**Issue by Edgar-P-yan** [microsoft/calculator#539]
In Programmer mode the result for 3000 * 80 is -22144, which is wrong, while in Standard and Scientific mode the result is correct (240000).

**Steps To Reproduce**
1. Switch to Programmer mode
2. Type 3000 * 80
(I did not test it on other machines)

**Screenshots**
![calc_bug_2](https://user-images.githubusercontent.com/35116136/58898846-f1f56e00-8714-11e9-9dbc-f14e14df3690.gif)

**Device and Application Information**
 - OS Build: 10.0.17134.0
 - Architecture: X64
 - Application Version: 10.1904.31.0
 - Region: ru-RU
 - Dev Version Installed: False

**Requested Assignment**
I'm just reporting this problem.  I don't want to fix it.

**Comment by MelulekiDube** [comment]
@Edgar-P-yan click on the word toggle button you will realize that the answers will be changing based on that. So from reading, i found out that the word type is 16 bits and thus 240000 will be evaluated to a 16-bit  binary number which is the 2's complement for-22144. 

I may be wrong about the explanation but yeah. Just ensure that the button you have D-Word to be safe.

**Comment by HowardWolosky** [comment]
@MelulekiDube is correct.  This is "By Design".  In your example, you were looking at numbers defined as `WORD`, so the negative answer that you're seeing is simply due to [integer overflow](https://en.wikipedia.org/wiki/Integer_overflow).

**Comment by Edgar-P-yan** [comment]
@HowardWolosky , @MelulekiDube. Now i see. Thank you for explaining
