### ISSUE TITLE
Date difference calculation wrong in certain cases

### ISSUE THREAD

**Issue by Bigpet** [microsoft/calculator#552]
**Describe the bug**
When calculating the difference between dates near the ends of months the results are sometimes wrong. I.E. 31st July - 30th December 2019 results in "5 moths; 613566756 weeks; 3 days".

**Steps To Reproduce**
1. Open Calculator 
2. Switch to date calculation mode
3. Go to the difference between dates - mode
4. Enter start-date 31st of July 2019
4. Enter end-date 30th of December 2019 (might be 31th of December to cause the bug in a different time-zone)

**Expected behavior**
Display a difference that is closer to reality. What the "correct" difference is, is sort of up to debate but 613566756 weeks is definitely not it. Fixing this bug results in "4 Months; 4 Weeks; 2 Days" which is kind of silly but technically correct according to the calculation method of "31st July + 4Months = November 30th" that Windows::Globalization::Calendar appears to use.

**Screenshots**

![image](https://user-images.githubusercontent.com/465677/59567223-26e5b700-906b-11e9-9e54-620e7aacce77.png)

**Device and Application Information**
 - OS Build: 10.0.18362.0
 - Architecture: X64
 - Application Version: 10.1904.42.0
 - Region: de-DE
 - Dev Version Installed: True

**Additional context**
Originally reported by /u/RLWLB2985 on /r/Windows10

**Requested Assignment**
If possible, I would like to fix this.
I have the minimal possible solution already implemented.

**Comment by ItzLevvie** [comment]
I was able to reproduce this issue on Windows 10 build 18362.175
![image](https://user-images.githubusercontent.com/11600822/59567378-3bbf4c00-9065-11e9-914e-74140bae1219.png)
![image](https://user-images.githubusercontent.com/11600822/59567390-47ab0e00-9065-11e9-9993-5e8b39b1ad5c.png)

**Comment by grochocki** [comment]
Thanks for the detailed report! I can reproduce the problem when trying to calculate the difference between July 31 to December 29 (Seattle, en-US).

**Comment by rudyhuyn** [comment]
> Enter end-date 30th of December 2019 (might be 31th of December to cause the bug in a different time-zone)

> I can reproduce the problem when trying to calculate the difference between July 31 to December 29 (Seattle, en-US).

This is an issue, the behavior of this feature shouldn't depend on the user's time zone but instead produce a consistent result. I will take a look.
