### ISSUE TITLE
Graphing feature not available

### ISSUE THREAD

**Issue by bludev** [microsoft/calculator#966]
Hello!
I ran the source code on my PC (VS 2019 16.4.3, Windows 10 1909 18363.592 x64, Windows 10 SDK 10.1.18362.1) but I can't see the graphing feature, because the IsGraphingModeAvailable() function in Common/NavCategory.cpp returns always false.
What are the minimum requirements to test this functionality?

**Comment by sanderl** [comment]
Hi bludev, thank you so much for your question. You are correct that IsGraphingModeAvailable() is returning false. Graphing mode is currently only available in Windows Insiders Program. In addition, please note that even if you have updated to the latest Windows Insiders build you will see a mock implementation of the graphing engine which is documented in more detail in our [ReadMe](https://github.com/microsoft/calculator/blob/master/README.md#graphing-mode).
